// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://se5szlzlangglj6uwhkw6am5lm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4c2btykrcvdmlotlczgd2nmury",
    "aws_content_delivery_bucket": "danielkretsch-amplify-hosting-test",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3b68acz7wsn1e.cloudfront.net"
};


export default awsmobile;
